import type { FaqAnswer } from './answers';

type AiEraFaqInput = Omit<
  FaqAnswer,
  'answer' | 'cacheMode' | 'answerSource' | 'skippedGroq' | 'visibility'
> & {
  visibility?: FaqAnswer['visibility'];
};

const sharedAiEraGuardrailsKo = [
  'AI가 절대 인간을 대체할 수 없다고 단정하지 않는다.',
  'AI로 팀 전체를 대체할 수 있다고 말하지 않는다.',
  'AI 사용을 실력의 대체물로 설명하지 않는다.',
  '주장 뒤에는 AskOosu, OOSU SALON, GfK, 팀 프로젝트, RAG 운영 같은 근거를 붙인다.',
];

const sharedAiEraGuardrailsEn = [
  'Do not claim AI can never replace humans.',
  'Do not imply Oosu can replace an entire team with AI.',
  'Do not frame AI usage as a substitute for skill.',
  'Tie claims back to evidence such as AskOosu, OOSU SALON, GfK, team projects, or RAG operations.',
];

export const AI_ERA_COMPETITIVENESS_FAQ_ANSWERS: FaqAnswer[] = [
  createAiEraAnswer({
    id: 'faq.ai_era.replace_developer.default',
    legacyIds: ['faq.ai_competitiveness.irreplaceable_work.default'],
    intentId: 'ai_era.replace_developer',
    entityId: 'ai_era_competitiveness',
    language: 'ko',
    quickLabel: 'AI 시대 경쟁력',
    displayQuestion:
      'AI가 개발자를 대체할 것 같은데, 우수는 어떻게 생각하나요?',
    alternativeDisplayQuestions: [
      '당신이 할 수 있는 일 중에서 AI가 대체하지 못하는 일은 무엇인가요?',
      'AI가 코드를 다 짜준다면 주니어 개발자를 뽑을 이유가 있나요?',
    ],
    patterns: [
      'AI가 개발자를 대체',
      '개발자 필요없어',
      'AI 시대 개발자',
      '개발자 살아남기',
      'AI 때문에 개발자 안 뽑는다',
      'AI가 대체하지 못하는 일',
      'AI 시대 개발자 경쟁력',
      'AI가 코드를 다 짜주면 주니어를 왜 뽑아',
    ],
    shortAnswer:
      'AI가 대체하기 어려운 일은 코드를 직접 치는 능력 하나가 아니라, AI 결과물을 현실의 사용자 문제와 제품 맥락에 맞게 판단하고 검증하는 일입니다.',
    defaultAnswer: [
      '저는 AI가 실행을 빠르게 만드는 건 사실이라고 생각합니다. 하지만 "무엇을 실행할지"와 "그 결과를 믿어도 되는지"는 여전히 사람의 일입니다.',
      '',
      'AI가 만든 결과물은 빠르지만, 실제 사용자 문제, 제품 맥락, UX 흐름, 신뢰 기준에 맞는지는 별도로 판단해야 합니다. AskOosu에서 RAG와 FAQ cache를 분리하고, Notion을 CMS로 두면서 PostgreSQL을 retrieval cache로 쓰는 결정도 AI가 옵션을 제안했더라도 최종 판단은 사람이 책임져야 하는 영역이었습니다.',
      '',
      '> AI는 실행 속도를 빌려줍니다. 하지만 방향, 감각, 검토는 여전히 사람의 일이고, 저는 그 부분을 계속 훈련하고 있습니다.',
      '',
      '그래서 저는 "AI가 개발자를 대체하느냐"보다 "AI를 잘 쓰는 개발자가 그렇지 않은 개발자를 대체하느냐"가 더 현실적인 질문이라고 봅니다.',
    ].join('\n'),
    detailedAnswer: [
      'AI가 대체하기 어려운 일을 신비한 인간 능력처럼 포장하고 싶지는 않습니다. 더 정확히는 AI가 아직 현실과 직접 연결되어 있지 않다는 점에서 출발하는 게 맞다고 봅니다.',
      '',
      'LLM은 방대한 지식을 가진 채 고립된 섬에 있는 존재와 비슷합니다. 지식은 많고 실행도 빠르지만, 실제 사용자가 어떤 순간에 불편을 느끼는지, 이 팀의 우선순위가 무엇인지, 어떤 표현이 신뢰를 잃게 만드는지는 직접 알지 못합니다.',
      '',
      '우수는 OOSU SALON을 운영하며 사용자 반응을 읽는 감각을 쌓았고, GfK에서 데이터 뒤의 맥락을 보는 훈련을 했습니다. 그 경험이 지금 AI 결과물을 검토하고 다듬는 기준이 됩니다.',
      '',
      '따라서 우수의 경쟁력은 AI와 경쟁하는 것이 아니라, AI를 실제 사용자·제품 맥락·품질 기준과 연결하는 데 있습니다.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.replace_developer.default',
      'ops.ai-agent-workflow.ko',
      'ops.product-build-loop.ko',
      'ops.code-review-with-ai.ko',
      'decision.why-not-overclaim-ai-era.ko',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'ai_usage',
      'profile',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.skill_atrophy.default',
    intentId: 'ai_era.skill_atrophy',
    entityId: 'ai_era_competitiveness',
    language: 'ko',
    quickLabel: 'AI와 실력',
    displayQuestion: 'AI 도구를 많이 쓰면 실력이 안 늘지 않나요?',
    alternativeDisplayQuestions: [
      'AI를 많이 쓰는데 본인이 직접 코드를 이해하고 작성할 수 있나요?',
      'AI 없이도 개발할 수 있나요?',
    ],
    patterns: [
      'AI 많이 쓰면 실력',
      'AI 의존',
      'AI 없으면 못 하나',
      '진짜 실력',
      'AI 기본기',
      '코드를 직접 짤 수 있는가',
      'AI를 쓰면 개발 실력이 부족한 것 아닌가',
    ],
    shortAnswer:
      'AI를 잘 쓰는 것과 AI에 의존하는 것은 다릅니다. 우수는 설계와 흐름을 먼저 이해하고, AI 결과를 검토하면서 구현 속도를 빌리는 쪽에 가깝습니다.',
    defaultAnswer: [
      '초기에는 우수도 AI가 준 코드를 그대로 쓰면 작동은 하는데, 왜 작동하는지 모르면 고칠 수 없다는 걸 경험했습니다. 그래서 지금은 방식이 달라졌습니다.',
      '',
      '먼저 목표, 수정 범위, 피해야 할 점, 테스트 기준을 정하고 AI에게 맡깁니다. 결과를 받은 뒤에는 실제 파일 구조를 참조했는지, API와 UI 필드가 맞는지, 보안 키나 민감 정보가 노출되지 않았는지를 확인합니다.',
      '',
      '> AI를 잘 검토할 수 있어야 잘 쓸 수 있습니다.',
      '',
      '이 검토를 하려면 결국 내가 알고 있어야 합니다. 그래서 AI는 이해의 대체물이 아니라 학습과 실행 속도를 높이는 증폭 도구에 가깝습니다.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.skill_atrophy.default',
      'ops.code-review-with-ai.ko',
      'postmortem.instagram-clone-fullstack-lessons.ko',
      'decision.why-not-overclaim-ai-era.ko',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'profile'],
    confidence: 0.91,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.competitiveness_source.default',
    legacyIds: ['faq.ai_competitiveness.real_competitor.default'],
    intentId: 'ai_era.competitiveness_source',
    entityId: 'ai_era_competitiveness',
    language: 'ko',
    quickLabel: '경쟁력',
    displayQuestion: '우수의 경쟁력은 AI 시대에 어디서 온다고 생각하나요?',
    alternativeDisplayQuestions: [
      '본인의 경쟁자는 누구라고 생각하나요?',
      'AI 시대에 왜 우수를 뽑아야 하나요?',
    ],
    patterns: [
      '경쟁력',
      '강점',
      'AI 시대 차별점',
      '왜 우수를 뽑아야',
      '우수 특징',
      '어떤 점이 남다른가',
      'AI와 경쟁',
      'AI가 경쟁자',
      'AI 시대 경쟁자',
      '본인의 경쟁자는 누구',
    ],
    shortAnswer:
      '우수의 경쟁력은 AI 자체와 경쟁하는 데 있지 않고, AI를 실제 사용자 문제와 제품 판단에 연결하는 속도와 검증 습관에서 옵니다.',
    defaultAnswer: [
      '세 가지에서 온다고 생각합니다.',
      '',
      '**하나, 연결된 경험입니다.** 고객 리서치, 데이터 분석, OOSU SALON 운영, UX/UI, Fullstack, AI/RAG가 따로 떨어진 이력이 아니라 다음 판단의 기준으로 이어져 있습니다.',
      '',
      '**둘, AI를 현실과 연결하는 감각입니다.** AI는 가능성을 제안하지만 그 가능성이 이 사용자, 이 팀, 이 프로젝트에 맞는지는 사람이 판단해야 합니다. 5년의 서비스 운영과 데이터 분석 경험이 그 기준을 만들었습니다.',
      '',
      '**셋, 빠른 실험 속도입니다.** Groq, pgvector, Cloudflare Tunnel, Vercel AI SDK 같은 도구를 읽는 데서 멈추지 않고 AskOosu를 만들며 실제 배포까지 연결했습니다.',
      '',
      '> AI 자체는 제 경쟁자가 아닙니다. 경쟁자는 AI를 잘 활용하는 사람들입니다. 저는 그 편에 있으려고 지금도 실험하고 있습니다.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.competitiveness_source.default',
      'decision.why-ai-native-working-thesis.ko',
      'project.askoosu.fact',
      'profile.learning_style',
      'career.timeline',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'profile',
      'career',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
    intentId: 'ai_competitiveness.ai_fluency_vs_dependency',
    entityId: 'ai_era_competitiveness',
    language: 'ko',
    quickLabel: 'AI fluency',
    displayQuestion: 'AI를 잘 쓰는 것과 AI에 의존하는 것은 어떻게 다른가요?',
    patterns: [
      'AI 의존',
      'AI를 잘 쓰는 것',
      'AI 없으면 개발 못 하나',
      'AI dependency',
      'AI fluency',
      'AI를 많이 쓰는 것과 의존하는 것 차이',
    ],
    shortAnswer:
      'AI 의존은 이해하지 못한 결과를 받아들이는 것이고, AI fluency는 목표와 검증 기준을 정한 뒤 결과를 책임지고 통합하는 것입니다.',
    defaultAnswer: [
      'AI에 의존하는 것은 결과를 이해하지 못한 채 받아들이는 것입니다. 반대로 AI를 잘 쓰는 것은 목표, 범위, 검증 기준을 먼저 정한 뒤 결과를 책임지고 통합하는 것입니다.',
      '',
      '우수는 AI에게 일을 맡길 때도 목표, 수정 범위, 금지사항, 테스트 기준을 먼저 정하려고 합니다. 그리고 결과를 실제 코드베이스와 제품 흐름 안에서 다시 확인합니다.',
      '',
      '> AI 코드는 초안이고, 제품에 들어가는 판단은 사람이 책임집니다.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
      'ops.ai-agent-workflow.ko',
      'ops.code-review-with-ai.ko',
      'ops.answer-quality-loop.ko',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsKo,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'askoosu'],
    confidence: 0.91,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.replace_developer.default',
    legacyIds: ['faq.ai_competitiveness.irreplaceable_work.default'],
    intentId: 'ai_era.replace_developer',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'AI-era edge',
    displayQuestion: 'Will AI replace developers? What does Oosu think?',
    alternativeDisplayQuestions: [
      "What can you do that AI can't replace?",
      'If AI writes code, why hire a junior developer?',
    ],
    patterns: [
      'AI replace developer',
      'developers becoming obsolete',
      'AI era developer',
      'developer job security',
      'why hire developers when AI exists',
      "what can you do that AI can't replace",
      'AI writes all the code',
    ],
    shortAnswer:
      "What AI can't replace is not simply typing code. It is judging and refining AI output against real user problems, product context, UX flow, and trust standards.",
    defaultAnswer: [
      'I think AI genuinely accelerates execution. But deciding what to execute, and whether the result is trustworthy enough for a product, is still human work.',
      '',
      'AI output can be fast, but it still has to be checked against real user problems, product context, UX flow, and trust standards. In AskOosu, AI could propose options, but decisions like separating RAG from FAQ cache or using Notion as CMS with PostgreSQL as the retrieval cache were judgments I had to own.',
      '',
      '> AI lends me execution speed. But direction, sensibility, and review are still human work. That is what I am actively training.',
      '',
      'So I think the more realistic question is not "will AI replace developers?" It is "will developers who use AI well replace those who do not?"',
    ].join('\n'),
    detailedAnswer: [
      'I would not frame this as mysterious human superiority. A more accurate framing is that AI is powerful, but disconnected from many real-world contexts.',
      '',
      'An LLM is like someone isolated on an island surrounded by enormous stacks of books. It has a lot of knowledge and speed, but it does not directly know what a real user finds frustrating, what this team needs this week, or which UI copy will lose trust.',
      '',
      'Running OOSU SALON trained me to read user reactions in real time. Working at GfK trained me to read context behind data. That is the standard I now use when reviewing and refining AI output.',
      '',
      'So Oosu is not trying to compete with AI. The goal is to connect AI to real users, product context, and responsible judgment.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.replace_developer.default',
      'ops.ai-agent-workflow.en',
      'ops.product-build-loop.en',
      'ops.code-review-with-ai.en',
      'decision.why-not-overclaim-ai-era.en',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'ai_usage',
      'profile',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.skill_atrophy.default',
    intentId: 'ai_era.skill_atrophy',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'AI and skill',
    displayQuestion:
      "Doesn't using AI tools a lot mean you're not actually developing your skills?",
    alternativeDisplayQuestions: [
      'Can you actually understand and write code yourself?',
      'Can you code without AI?',
    ],
    patterns: [
      'AI dependency skill atrophy',
      'real skills',
      'can you code without AI',
      'AI fluency vs skill',
      'using AI too much',
      'does Oosu actually code',
    ],
    shortAnswer:
      'Using AI well is different from depending on AI. Oosu tries to understand the design and flow first, then borrow AI speed while reviewing the result.',
    defaultAnswer: [
      'Early on, I experienced the exact risk: AI-generated code could run, but when I did not understand why it ran, I could not fix it when things broke. That frustration shaped my current workflow.',
      '',
      'Now I define the goal, edit scope, constraints, and test criteria before delegating to AI. Then I check whether the result references the real file structure, whether API and UI fields match, and whether any secrets or sensitive data are exposed.',
      '',
      '> To use AI well, you have to be capable of reviewing it well.',
      '',
      'That review requires me to actually know what is happening. So AI is not a replacement for understanding; it is an amplifier for learning and execution speed.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.skill_atrophy.default',
      'ops.code-review-with-ai.en',
      'postmortem.instagram-clone-fullstack-lessons.en',
      'decision.why-not-overclaim-ai-era.en',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'profile'],
    confidence: 0.91,
  }),
  createAiEraAnswer({
    id: 'faq.ai_era.competitiveness_source.default',
    legacyIds: ['faq.ai_competitiveness.real_competitor.default'],
    intentId: 'ai_era.competitiveness_source',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'Competitive edge',
    displayQuestion:
      "Where does Oosu's competitive edge come from in the AI era?",
    alternativeDisplayQuestions: [
      'Who do you think your competitors are?',
      'Why hire Oosu in the AI era?',
    ],
    patterns: [
      'competitive advantage',
      'strengths',
      'AI era differentiation',
      'why hire Oosu',
      'what makes Oosu different',
      'AI is your competitor',
      'competing with AI',
      'who are your competitors',
    ],
    shortAnswer:
      "Oosu's edge is not competing with AI itself. It is the speed and review habit of connecting AI to real user problems and product judgment.",
    defaultAnswer: [
      'I think it comes from three things.',
      '',
      '**One: connected experience.** Customer research, data analytics, running OOSU SALON, UX/UI, Fullstack, and AI/RAG are not separate chapters. Each stage became a standard for the next.',
      '',
      '**Two: the instinct to connect AI to reality.** AI suggests possibilities, but judging whether those possibilities fit this user, this team, and this product comes from lived experience.',
      '',
      '**Three: speed of experimentation.** Groq, pgvector, Cloudflare Tunnel, and Vercel AI SDK were not just things I read about. I used them while building AskOosu and connected them to production.',
      '',
      '> AI itself is not my competitor. Developers who use AI effectively are my competitors. I am preparing to be on that side.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_era.competitiveness_source.default',
      'decision.why-ai-native-working-thesis.en',
      'project.askoosu.fact',
      'profile.learning_style',
      'career.timeline',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: [
      'ai_era_competitiveness',
      'profile',
      'career',
      'askoosu',
    ],
    confidence: 0.92,
  }),
  createAiEraAnswer({
    id: 'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
    intentId: 'ai_competitiveness.ai_fluency_vs_dependency',
    entityId: 'ai_era_competitiveness',
    language: 'en',
    quickLabel: 'AI fluency',
    displayQuestion:
      "What's the difference between using AI well and being dependent on AI?",
    patterns: [
      'AI dependency',
      'using AI well',
      "can't code without AI",
      'AI fluency',
      'AI fluency vs dependency',
    ],
    shortAnswer:
      'AI dependency means accepting results without understanding them. AI fluency means defining goals and validation criteria, then taking responsibility for integration.',
    defaultAnswer: [
      'Being dependent on AI means accepting results without understanding them. Using AI well means defining the goal, scope, and validation criteria first, then taking responsibility for integrating the result.',
      '',
      'Oosu tries to define the objective, modification scope, things to avoid, and test criteria before handing work to AI. Then the result is reviewed inside the actual codebase and product flow.',
      '',
      '> AI code is a draft; the judgment that goes into the product is still mine.',
    ].join('\n'),
    renderSpec: {
      layout: 'text_only',
      density: 'standard',
      components: ['SourceBadgeList'],
    },
    visualBlocks: [{ type: 'sourceBadges' }],
    sourceChunkIds: [
      'faq.ai_competitiveness.ai_fluency_vs_dependency.default',
      'ops.ai-agent-workflow.en',
      'ops.code-review-with-ai.en',
      'ops.answer-quality-loop.en',
    ],
    hasTodo: false,
    freshness: 'stable',
    guardrails: sharedAiEraGuardrailsEn,
    matchedEntityIds: ['ai_era_competitiveness', 'ai_usage', 'askoosu'],
    confidence: 0.91,
  }),
];

function createAiEraAnswer(input: AiEraFaqInput): FaqAnswer {
  return {
    ...input,
    answer: input.defaultAnswer,
    cacheMode: 'direct_cache',
    answerSource: 'faq_cache',
    skippedGroq: true,
    visibility: input.visibility ?? 'public',
  };
}
